-- Create tables for the e-commerce platform

-- Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT,
    category TEXT,
    brand TEXT,
    price NUMERIC NOT NULL,
    price_discount NUMERIC,
    rating NUMERIC DEFAULT 0,
    images TEXT[] DEFAULT '{}',
    description TEXT,
    gender TEXT,
    state TEXT,
    colors TEXT[] DEFAULT '{}',
    sizes TEXT[] DEFAULT '{}',
    technical_specs JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    image TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Users Table (to replace localStorage users_db)
CREATE TABLE IF NOT EXISTS public.users (
    id TEXT PRIMARY KEY, -- using TEXT to match the 'user-timestamp' format or UUID
    name TEXT,
    email TEXT UNIQUE NOT NULL,
    password TEXT, -- In a real app, this should be hashed. For this migration of mock data, we keep it as is.
    phone TEXT,
    address TEXT,
    bairro TEXT,
    cidade TEXT,
    cep TEXT,
    role TEXT DEFAULT 'Cliente',
    status TEXT DEFAULT 'Ativo',
    provider TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY,
    customer TEXT,
    date TEXT, -- Keeping as text to match DD/MM/YYYY format in app, or could use DATE
    total NUMERIC,
    status TEXT,
    items JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Create policies (For this demo/migration, we will be permissive to ensure the app works immediately)
-- In production, you would restrict 'write' operations to admin users.

-- Products: Everyone can read, anyone can insert/update/delete (for the admin panel to work without complex auth setup yet)
CREATE POLICY "Public products are viewable by everyone" ON public.products FOR SELECT USING (true);
CREATE POLICY "Products are editable by everyone" ON public.products FOR ALL USING (true);

-- Categories: Everyone can read, anyone can edit
CREATE POLICY "Public categories are viewable by everyone" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Categories are editable by everyone" ON public.categories FOR ALL USING (true);

-- Users: Everyone can read/edit (to allow login/register to work with this table)
CREATE POLICY "Users are viewable by everyone" ON public.users FOR SELECT USING (true);
CREATE POLICY "Users are editable by everyone" ON public.users FOR ALL USING (true);

-- Orders: Everyone can read/edit
CREATE POLICY "Orders are viewable by everyone" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Orders are editable by everyone" ON public.orders FOR ALL USING (true);
