ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Ativo';

CREATE TABLE IF NOT EXISTS public.slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subtitle TEXT,
    title TEXT,
    description TEXT,
    image TEXT,
    link TEXT,
    button_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.featured_collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    discount NUMERIC,
    image TEXT,
    link TEXT,
    link_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.slides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.featured_collections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Slides are viewable by everyone" ON public.slides FOR SELECT USING (true);
CREATE POLICY "Slides are editable by everyone" ON public.slides FOR ALL USING (true);

CREATE POLICY "Featured Collections are viewable by everyone" ON public.featured_collections FOR SELECT USING (true);
CREATE POLICY "Featured Collections are editable by everyone" ON public.featured_collections FOR ALL USING (true);

INSERT INTO public.slides (subtitle, title, description, image, link, button_text)
VALUES
    ('Melhores ofertas personalizadas', 'Queima de estoque Nike 🔥', 'Consequat culpa exercitation mollit nisi excepteur do do tempor laboris eiusmod irure consectetur.', '/images/slides/home-slide-1.jpeg', '/products', 'Ver Ofertas'),
    ('Coleção de Verão', 'Novas Cores e Estilos ☀️', 'Aproveite o verão com o melhor estilo. Conforto e design exclusivo para você.', '/images/slides/home-slide-2.jpeg', '/products', 'Ver Ofertas'),
    ('Lançamentos Exclusivos', 'Tênis para Performance 🏃', 'Tecnologia de ponta para seus treinos. Supere seus limites com a nova coleção.', '/images/slides/home-slide-3.jpeg', '/products', 'Comprar Agora'),
    ('Oferta Especial', 'Descontos de até 50% 🏷️', 'Não perca as últimas unidades com preços imperdíveis. Garanta já o seu.', '/images/slides/home-slide-4.jpeg', '/products', 'Conferir');

INSERT INTO public.featured_collections (title, discount, image, link, link_text)
VALUES
    ('Novo drop Supreme', 30, '/images/products/star-wars-storm.png', '/products', 'Comprar'),
    ('Coleção Adidas', 30, '/images/icons/ddd 1.png', '/products?brand=Adidas', 'Comprar'),
    ('Novo Beats Bass', 30, '/images/products/collection-3.png', '/products?category=Headphones', 'Comprar');

UPDATE public.categories SET status = 'Ativo' WHERE status IS NULL;
